CREATE TYPE CTYPE 
(
	STR VARCHAR2(10),
	NUM NUMBER
);

CREATE TYPE CTYPE_TAB AS TABLE OF CTYPE;

CREATE OR REPLACE FUNCTION GEN_ROWS(NROWS NUMBER) RETURN CTYPE_TAB PIPELINED AS
BEGIN
  FOR i IN 1 .. NROWS LOOP
    PIPE ROW(CTYPE('ROW'||(i-1), i));   
  END LOOP;

  RETURN;
END;

CREATE OR REPLACE FUNCTION INT_SET(LEN NUMBER) RETURN INT_TAB PIPELINED AS
BEGIN
  FOR i IN 1 .. LEN LOOP
    PIPE ROW(i * 100);   
  END LOOP;

  RETURN;
END;

CREATE OR REPLACE FUNCTION NUM_SUM(ANUM NUMBER, BNUM NUMBER) RETURN NUMBER AS
BEGIN
  RETURN ANUM + BNUM;
END;

CREATE OR REPLACE PROCEDURE OUT_TEXT(TXT OUT VARCHAR2) AS
BEGIN
  TXT := 'out_text_result';
END;

